<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>drive on Silviu's Blog</title><link>http://silviuvulcan.ro/blog/tags/drive/</link><description>Recent content in drive on Silviu's Blog</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Fri, 03 Apr 2015 10:16:22 +0000</lastBuildDate><atom:link href="http://silviuvulcan.ro/blog/tags/drive/index.xml" rel="self" type="application/rss+xml"/><item><title>Running gcp.py from cron</title><link>http://silviuvulcan.ro/blog/2015/04/03/running-gcp-py-from-cron/</link><pubDate>Fri, 03 Apr 2015 10:16:22 +0000</pubDate><guid>http://silviuvulcan.ro/blog/2015/04/03/running-gcp-py-from-cron/</guid><description>On my backup server I run gcp.py from gdatacopier to backup my google docs. I had to fix two issues in order to get it to run from a bash script:
the PYTHONPATH had to be exported prior to running, or the script will fail because it requires gdata-python-client the LANG envronment has to be set otherwise it will spill the following error in the log (if you bother to log the output from cron that is, otherwise it will just not work and you won&amp;rsquo;t know why, because the script works fine when ran manually) Traceback (most recent call last): File &amp;#34;/usr/local/bin/gcp.</description></item></channel></rss>